[programs.localnet]
error = "8dhKfFjFuYiQGSorapkCMY4btfkxq3w1nAzh14im7dbU"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/webdev522/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
